### ISSUE TITLE
houdini '.hip' 파일 사용자권한 잠금

### ISSUE THREAD

**Issue by kokbee** [digital-idea/dilink#12]
hip 파일을 dilink 실행 후, 저장하면 권한이 644로 적용

**Comment by khw7096** [comment]
오~ 드뎌 후디니도 dilink를 사용하나요?
어떤 권한을 원해요?

**Comment by khw7096** [comment]
gnome-terminal을 새로 띄우면 권한이 줄어든다. 664 -> 644
mate-terminal 로 명령을 바꾼다. 664 -> 664
