### ISSUE TITLE
mate-terminal 의 경우 프로파일을 적용해줘야한다.

### ISSUE THREAD

**Issue by kokbee** [digital-idea/dilink#25]
후디니도 마야와 같은 증상을 보임

**Comment by kokbee** [comment]
프로파일이 필요한 경우는 bash 위치를 못잡을 때만 필요함
디아이의 경우는 잡혀있기에 필요가 없음

**Comment by kokbee** [comment]
커맨드 명령어를 "-e" 에서 "-x"로 변경 후 실행하니 적용됨

**Comment by kokbee** [comment]
maya, houdini, usd 정상 작동

**Comment by khw7096** [comment]
+2
