### ISSUE TITLE
alembic view 제거

### ISSUE THREAD

**Issue by kokbee** [digital-idea/dilink#39]

**Comment by khw7096** [comment]
왜 제거해야하는지 이유가 적혀있지 않아요. 이 이슈는 닫고 다시 반복이슈가 나오면 다시 열겠습니다.

**Comment by kokbee** [comment]
> 왜 제거해야하는지 이유가 적혀있지 않아요. 이 이슈는 닫고 다시 반복이슈가 나오면 다시 열겠습니다.

해당이슈는 alembic view가 usdView로 지원이 가능해져서 제가 적어둿던거 같아요~
이슈는 열어두고 안닫았나 봐요 ㅎ

**Comment by khw7096** [comment]
리플 달아줘서 고마와요~
