### ISSUE TITLE
롤백하기: 토론이후

### ISSUE THREAD

**Issue by khw7096** [digital-idea/dilink#44]
https://github.com/digital-idea/dilink/commit/c7927552b82f974ca5f7ee3a9c17e034c3bf2474

**Comment by kokbee** [comment]
이거 러스터 땡겨오는거라 작업자들 여럿이 접속하면 느려지지 않나요?
그리고 해당이슈의 rv경로는 rv가 설치된 경로만 땡겨와야하고 수정해야하는건 환경변수가 맞지 않나 생각합니다 ㅇ_ㅇ

**Comment by khw7096** [comment]
저도 그렇게 생각해요. 그래서 토론해보려구요~
